import type { Product, Order, Delivery, Business } from '@/types';

export const demoProducts: Product[] = [
  {
    id: 'demo-1',
    name: 'Fresh Oranges',
    description: 'Sweet, juicy oranges from local farms',
    price: 1500,
    currency: 'NGN',
    imageUrl: 'https://images.pexels.com/photos/38665120/pexels-photo-38665120.jpeg?auto=compress&cs=tinysrgb&h=400&w=400',
    category: 'Produce',
    unit: 'bag',
    inStock: true,
    available: true,
  },
  {
    id: 'demo-2',
    name: 'Beans (Brown)',
    description: 'Quality brown beans, perfect for cooking',
    price: 3200,
    currency: 'NGN',
    imageUrl: 'https://images.pexels.com/photos/36930125/pexels-photo-36930125.jpeg?auto=compress&cs=tinysrgb&h=400&w=400',
    category: 'Staples',
    unit: 'kg',
    inStock: true,
    available: true,
  },
  {
    id: 'demo-3',
    name: 'Groundnuts (Roasted)',
    description: 'Freshly roasted groundnuts from Enugu',
    price: 800,
    currency: 'NGN',
    imageUrl: 'https://images.pexels.com/photos/39289748/pexels-photo-39289748.jpeg?auto=compress&cs=tinysrgb&h=400&w=400',
    category: 'Snacks',
    unit: 'pack',
    inStock: true,
    available: true,
  },
  {
    id: 'demo-4',
    name: 'Agbalumo (African Star Apple)',
    description: 'Seasonal fresh agbalumo from Abuja markets',
    price: 1200,
    currency: 'NGN',
    imageUrl: 'https://images.pexels.com/photos/28752785/pexels-photo-28752785.jpeg?auto=compress&cs=tinysrgb&h=400&w=400',
    category: 'Produce',
    unit: 'pack',
    inStock: true,
    available: true,
  },
  {
    id: 'demo-5',
    name: 'Snacks Bundle',
    description: 'Popular snacks from local convenience stores',
    price: 2500,
    currency: 'NGN',
    imageUrl: 'https://images.pexels.com/photos/31359734/pexels-photo-31359734.jpeg?auto=compress&cs=tinysrgb&h=400&w=400',
    category: 'Snacks',
    unit: 'bundle',
    inStock: true,
    available: true,
  },
  {
    id: 'demo-6',
    name: 'Market Day Fresh Vegetables',
    description: 'Assorted fresh vegetables from local vendors',
    price: 2000,
    currency: 'NGN',
    imageUrl: 'https://images.pexels.com/photos/8476594/pexels-photo-8476594.jpeg?auto=compress&cs=tinysrgb&h=400&w=400',
    category: 'Produce',
    unit: 'basket',
    inStock: true,
    available: true,
  },
  {
    id: 'demo-7',
    name: 'Fried Plantain Chips',
    description: 'Crispy fried plantain chips, locally made',
    price: 600,
    currency: 'NGN',
    imageUrl: 'https://images.pexels.com/photos/3807030/pexels-photo-3807030.jpeg?auto=compress&cs=tinysrgb&h=400&w=400',
    category: 'Snacks',
    unit: 'pack',
    inStock: true,
    available: true,
  },
  {
    id: 'demo-8',
    name: 'Grocery Essentials Pack',
    description: 'Curated pack of everyday grocery essentials',
    price: 5500,
    currency: 'NGN',
    imageUrl: 'https://images.pexels.com/photos/2564460/pexels-photo-2564460.jpeg?auto=compress&cs=tinysrgb&h=400&w=400',
    category: 'Groceries',
    unit: 'pack',
    inStock: false,
    available: false,
  },
];

export const demoBusinesses: Business[] = [
  { id: 'biz-1', name: 'Bauchi Fresh Mart', address: 'Wunti, Bauchi', phone: '+234 803 111 0001', email: 'freshmart@squadlink.demo', isVerified: true, verificationStatus: 'VERIFIED' },
  { id: 'biz-2', name: 'Yam Hausa Kitchen', address: 'Gidan Mai, Bauchi', phone: '+234 803 111 0002', email: 'yamhausa@squadlink.demo', isVerified: true, verificationStatus: 'VERIFIED' },
  { id: 'biz-3', name: 'City Electronics Hub', address: 'Gidan Dan Fili, Bauchi', phone: '+234 803 111 0003', email: 'electronics@squadlink.demo', isVerified: true, verificationStatus: 'VERIFIED' },
  { id: 'biz-4', name: 'Everyday Supermarket', address: 'Adamu Juma, Bauchi', phone: '+234 803 111 0004', email: 'everyday@squadlink.demo', isVerified: true, verificationStatus: 'VERIFIED' },
  { id: 'biz-5', name: 'CarePlus Pharmacy', address: 'Ran Road, Bauchi', phone: '+234 803 111 0005', email: 'careplus@squadlink.demo', isVerified: true, verificationStatus: 'VERIFIED' },
  { id: 'biz-6', name: 'Smart Supplies Store', address: 'Yelwa, Bauchi', phone: '+234 803 111 0006', email: 'smartsupplies@squadlink.demo', isVerified: false, verificationStatus: 'PENDING' },
  { id: 'biz-7', name: 'Fresh Harvest Farms', address: 'Miri, Bauchi', phone: '+234 803 111 0007', email: 'harvest@squadlink.demo', isVerified: true, verificationStatus: 'VERIFIED' },
  { id: 'biz-8', name: 'Quick Bite Shawarma', address: 'Ahmadu Bello Way, Bauchi', phone: '+234 803 111 0008', email: 'quickbite@squadlink.demo', isVerified: true, verificationStatus: 'VERIFIED' },
];

export const demoOrders: Order[] = [
  {
    id: 'ord-001',
    status: 'PENDING',
    items: [
      { productId: 'demo-1', name: 'Fresh Oranges', quantity: 2, price: 1500, subtotal: 3000 },
      { productId: 'demo-6', name: 'Market Day Fresh Vegetables', quantity: 1, price: 2000, subtotal: 2000 },
    ],
    subtotal: 5000,
    deliveryFee: 500,
    vat: 375,
    total: 5875,
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'ord-002',
    status: 'CONFIRMED',
    items: [
      { productId: 'demo-2', name: 'Beans (Brown)', quantity: 3, price: 3200, subtotal: 9600 },
    ],
    subtotal: 9600,
    deliveryFee: 500,
    vat: 720,
    total: 10820,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 'ord-003',
    status: 'PREPARING',
    items: [
      { productId: 'demo-5', name: 'Snacks Bundle', quantity: 2, price: 2500, subtotal: 5000 },
      { productId: 'demo-7', name: 'Fried Plantain Chips', quantity: 3, price: 600, subtotal: 1800 },
    ],
    subtotal: 6800,
    deliveryFee: 500,
    vat: 510,
    total: 7810,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
  },
  {
    id: 'ord-004',
    status: 'READY_FOR_PICKUP',
    items: [
      { productId: 'demo-3', name: 'Groundnuts (Roasted)', quantity: 5, price: 800, subtotal: 4000 },
    ],
    subtotal: 4000,
    deliveryFee: 500,
    vat: 300,
    total: 4800,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: 'ord-005',
    status: 'OUT_FOR_DELIVERY',
    items: [
      { productId: 'demo-4', name: 'Agbalumo (African Star Apple)', quantity: 4, price: 1200, subtotal: 4800 },
    ],
    subtotal: 4800,
    deliveryFee: 500,
    vat: 360,
    total: 5660,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    id: 'ord-006',
    status: 'DELIVERED',
    items: [
      { productId: 'demo-1', name: 'Fresh Oranges', quantity: 1, price: 1500, subtotal: 1500 },
      { productId: 'demo-7', name: 'Fried Plantain Chips', quantity: 2, price: 600, subtotal: 1200 },
    ],
    subtotal: 2700,
    deliveryFee: 500,
    vat: 202,
    total: 3402,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 'ord-007',
    status: 'DELIVERED',
    items: [
      { productId: 'demo-2', name: 'Beans (Brown)', quantity: 2, price: 3200, subtotal: 6400 },
    ],
    subtotal: 6400,
    deliveryFee: 500,
    vat: 480,
    total: 7380,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
];

export const demoDeliveries: Delivery[] = [
  {
    id: 'del-001',
    orderId: 'ord-004',
    status: 'PICKED_UP',
    pickupAddress: 'Yelwa, Bauchi',
    deliveryAddress: 'Gidan Mai, Bauchi',
    assignedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    pickedUpAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
  {
    id: 'del-002',
    orderId: 'ord-005',
    status: 'IN_TRANSIT',
    pickupAddress: 'Wunti, Bauchi',
    deliveryAddress: 'Ran Road, Bauchi',
    assignedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    pickedUpAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
  {
    id: 'del-003',
    orderId: 'ord-006',
    status: 'DELIVERED',
    pickupAddress: 'Gidan Dan Fili, Bauchi',
    deliveryAddress: 'Adamu Juma, Bauchi',
    assignedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    pickedUpAt: new Date(Date.now() - 1000 * 60 * 60 * 23).toISOString(),
    deliveredAt: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
  },
  {
    id: 'del-004',
    orderId: 'ord-007',
    status: 'DELIVERED',
    pickupAddress: 'Miri, Bauchi',
    deliveryAddress: 'Ahmadu Bello Way, Bauchi',
    assignedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    pickedUpAt: new Date(Date.now() - 1000 * 60 * 60 * 47).toISOString(),
    deliveredAt: new Date(Date.now() - 1000 * 60 * 60 * 46).toISOString(),
  },
];
